### ISSUE TITLE
请问AttrListGen.py中的filelist指的是什么，detlist是怎么产生的？

### ISSUE THREAD

**Issue by joetitor** [WynMew/FaceAttribute#1]

**Comment by WynMew** [comment]
filelist 是由detMTCNN_celebA.py做face detection之后的有人脸的图像列表，可以使用bash脚本产生。
然后使用AttrListGen.py去celebA的label列表中查找文件名和对应的label.

**Comment by Asunany** [comment]
filelist就是用于存放图片名称的一个文件。
送给AttrListGen.py,用于生成每个文件对应的标签。
