### ISSUE TITLE
what is the celebATest?

### ISSUE THREAD

**Issue by xxllp** [WynMew/FaceAttribute#2]
这个文件是啥

**Comment by DanielXu123** [comment]
@xxllp 
Hi 想问下这个网络你有复现成功吗

**Comment by Asunany** [comment]
https://zhuanlan.zhihu.com/p/35975956

CelebA是CelebFaces Attribute的缩写，意即名人人脸属性数据集，其包含10,177个名人身份的202,599张人脸图片，每张图片都做好了特征标记，包含人脸bbox标注框、5个人脸特征点坐标以及40个属性标记，CelebA由香港中文大学开放提供，广泛用于人脸相关的计算机视觉训练任务，可用于人脸属性标识训练、人脸检测训练以及landmark标记等，官方网址：Large-scale CelebFaces Attributes (CelebA) Datase
