### ISSUE TITLE
‘Save_list’ , in ‘detMTCNN_celebA.py’,  doesn't seem to work?

### ISSUE THREAD

**Issue by konioyxgq** [WynMew/FaceAttribute#5]
‘Save_list’ , in ‘detMTCNN_celebA.py’,  doesn't seem to work?  
f = open(Save_list, 'wt')

**Comment by WynMew** [comment]
> ‘Save_list’ , in ‘detMTCNN_celebA.py’, doesn't seem to work?
> f = open(Save_list, 'wt')

It's just a plain text file, you may try any other method you see fit.
