### ISSUE TITLE
Torch img process before send to model

### ISSUE THREAD

**Issue by DanielXu123** [WynMew/FaceAttribute#6]

**Comment by DanielXu123** [comment]
> Hi, WynMew.
> 
> Thanks for your work, really appreciate.
> 
> I've succesfully trained the network and save the model into onnx model as well, cause I need to transfer the model to caffemodel for other use.
> 
> There's a question about the test process.
> In AttrEvaRes18_256V0.py,line 67 68
> `inp = cv2.resize(input, (256, 256))`
> `imgI = (torch.from_numpy(inp.transpose((2, 0, 1))).float().div(255.0).unsqueeze_(0)-0.5)/0.5`
> 
> what's excatly does line 68 do?
> I tried to follow the steps as line 68 in caffe, but got the results not as the same as the test results of pytorhc model (pth).
> 
> That's what I did for the img process before send to caffe forward test
> 
> `img = cv2.imread(image_file)`
> `img = cv2.resize(img, (256,256))`
> `transformer = caffe.io.Transformer({'data': net.blobs['data'].data.shape})`
> `transformer.set_transpose('data', (2, 0, 1))`
> `transformed_image = transformer.preprocess('data', img)`
> `transformed_image = transformed_image /255.0`
> `transformed_image = (transformed_image - 0.5) /0.5`
> `net.blobs['data'].data[...] = transformed_image`

**Comment by Asunany** [comment]
```
    test_img_dir = "test_imgs"
    device = "cuda"
    with torch.no_grad():
        for img_file in os.listdir(test_img_dir):
            img_file_path = os.path.join(test_img_dir,img_file)
            img_data = cv2.imread(img_file_path)
            raw_img_h, raw_img_w, _ = img_data.shape
            using_img = img_data.copy()
            using_img = using_img.reshape(1, img_data.shape[0], img_data.shape[1], img_data.shape[2])
            using_img = np.asarray(using_img, dtype=np.float32)
            using_img = torch.from_numpy(using_img)
            using_img = using_img.permute(0,3,2,1)
            using_img = using_img.to(device)
            start_time = time.time()
            AttractivePre, EyeGlassesPre, MalePre, MouthOpenPre, SmilingPre, YoungPre = model(using_img)
            cost_time = (time.time() - start_time)*1000
            print("cost_time:{}ms".format(cost_time))
            print("\n{}预测结果：".format(img_file))
            print("Attractive [2], EyeGlasses [15], Male [20], MouthOpen [21], Smiling [31], Young [39]:\n",
                torch.argmax(AttractivePre).cpu().item(),'\t',
                torch.argmax(EyeGlassesPre).cpu().item(),'\t',
                torch.argmax(MalePre).cpu().item(),'\t',
                torch.argmax(MouthOpenPre).cpu().item(),'\t',
                torch.argmax(SmilingPre).cpu().item(),'\t',
                torch.argmax(YoungPre).cpu().item())
```
